version: '3'
services:
  airflow-worker-simulation:
    build: .
    command: celery worker -q simulation,general
    user: root
    healthcheck:
      test:
        - "CMD-SHELL"
        - 'celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@${POSTGRES_ADDRESS:-postgres}/airflow"
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@${POSTGRES_ADDRESS:-postgres}/airflow"
      AIRFLOW__CELERY__RESULT_BACKEND: "db+postgresql://airflow:airflow@${POSTGRES_ADDRESS:-postgres}/airflow"
      AIRFLOW__CELERY__BROKER_URL: "redis://:@${REDIS_ADDRESS:-redis:6379}/0"
      AIRFLOW__CORE__FERNET_KEY: "${AIRFLOW__CORE__FERNET_KEY}"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
      AIRFLOW__SMTP__SMTP_HOST: smtp.gmail.com
      AIRFLOW__SMTP__SMTP_STARTTLS: True
      AIRFLOW__SMTP__SMTP_SSL: False
      AIRFLOW__SMTP__SMTP_USER: "${GMAIL_ADDRESS}"
      AIRFLOW__SMTP__SMTP_PASSWORD: "${GMAIL_PASSWORD}"
      AIRFLOW__SMTP__SMTP_PORT: 587
      AIRFLOW__SMTP__SMTP_MAIL_FROM: "${GMAIL_ADDRESS}"
      AIRFLOW__LOGGING__REMOTE_LOGGING: True
      AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER: s3://alplakes-eawag/airflow/logs
      AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID: ALPLAKES_S3_CONN
      AIRFLOW__LOGGING__ENCRYPT_S3_LOGS: False
      AIRFLOW_CONN_ALPLAKES_S3_CONN: "s3://${AWS_ACCESS_KEY_ID}:${AWS_SECRET_ACCESS_KEY}@S3"
      _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-}
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AIRFLOW_VAR_AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AIRFLOW_VAR_AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AIRFLOW_VAR_COSMO_FTP_PASSWORD: "${COSMO_FTP_PASSWORD}"
      AIRFLOW_VAR_METEO_FTP_PASSWORD: "${METEO_FTP_PASSWORD}"
      AIRFLOW_VAR_FILESYSTEM: "${FILESYSTEM}"
      AIRFLOW_VAR_API_PASSWORD: "${API_PASSWORD}"
      # Required to handle warm shutdown of the celery workers properly
      # See https://airflow.apache.org/docs/docker-stack/entrypoint.html#signal-propagation
      DUMB_INIT_SETSID: "0"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - "${FILESYSTEM}:/opt/airflow/filesystem"
      - /var/run/docker.sock:/var/run/docker.sock
