version: '3.7'
services:
    remote_worker_3:
        image: worker-simulation:latest
        build:
          context: .
          args:
            github_token: ${GITHUB_TOKEN}
        restart: always
        external_links:
            - redis_1:redis
        networks:
            - sample_project_default
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
        volumes:
          - ./airflow/dags:/usr/local/airflow/dags
        env_file:
            - env.list
        command: worker -q simulation
        stdin_open: true
        tty: true
networks:
    sample_project_default:
        external: true

